export const API_ENDPOINTS = {
  authRegister: "/auth/register",
  authLogin: "/auth/login",
  authLogout: "/auth/logout",
  authMe: "/auth/me",
  usersProfile: "/users/profile",
  usersList: "/users",
  health: "/health",
  config: "/config",
  generate: "/generate",
  workflow: "/workflow",
  campaign: "/campaign",
  assets: "/assets",
  brands: "/brands",
  analyticsSummary: "/analytics/summary",
  analyticsDashboard: "/analytics/dashboard",
  analyticsQuery: "/analytics/query",
  analyticsHealth: "/analytics/health",
  markdownReport: "/reports/markdown",
  latestReports: "/reports/latest",
  storageRecords: "/storage/records",
  rbacRoles: "/rbac/roles",
  rbacPermissions: "/rbac/permissions",
  rbacMe: "/rbac/me",
  userRole: (userId: string) => `/users/${encodeURIComponent(userId)}/role`,
} as const;

export const REPORT_TYPES = [
  "workflow_report",
  "campaign_report",
  "generation_report",
  "asset_report",
  "executive_summary",
  "tracking_report",
  "cost_report",
  "media_report",
  "image_prompt_report",
  "image_prompt_validation_report",
  "visual_style_report",
  "storyboard_report",
  "video_script_report",
  "video_prompt_report",
] as const;

export const NAV_ITEMS = [
  { id: "dashboard", label: "Dashboard", hint: "Overview", anyOf: ["analytics:read"] },
  { id: "content", label: "Content Studio", hint: "Generate", permission: "generation:create" },
  { id: "workflow", label: "Workflow Center", hint: "Orchestrate", permission: "workflow:run" },
  { id: "campaign", label: "Campaign Studio", hint: "Compose", permission: "campaign:create" },
  { id: "assets", label: "Asset Studio", hint: "Coordinate", permission: "asset:create" },
  { id: "reports", label: "Reports Center", hint: "Markdown", permission: "report:read" },
  { id: "storage", label: "Storage Explorer", hint: "Browse", permission: "storage:read" },
  { id: "analytics", label: "Analytics Center", hint: "Metrics", permission: "analytics:read" },
  { id: "governance", label: "Governance Center", hint: "Review", anyOf: ["analytics:read", "report:read"] },
  { id: "config", label: "System Config", hint: "Settings", permission: "system:read" },
] as const;
